[fix] YouTube Mobile Locale URL Doesn't Exist
Anarios/return-youtube-dislike pull request #281
Opened 2021-12-12 22:58 UTC by evanreichard

On m.youtube.com, the locale URL doesn't exist. This will throw an invalid URL (passes undefined to the URL constructor).

On quick glance it doesn't appear that there's a good alternative on mobile, so I just fallback to 'en'.

2021-12-13 03:41 UTC, cupiditys commented
navigator.language works on m.youtube.com

2021-12-13 05:51 UTC, DARKDRAGON532 commented
does `document.documentElement.lang` not work on mobile?

> navigator.language works on m.youtube.com

2021-12-13 06:11 UTC, cupiditys commented
> does `document.documentElement.lang` not work on mobile?
> 
> > navigator.language works on m.youtube.com

yea it doesnt work

2021-12-13 06:13 UTC, cupiditys commented
just comes back as nothing
![image](https://user-images.githubusercontent.com/66990287/145761532-540ab84f-0261-4ff7-8d23-4f8cea3076ed.png)

2021-12-13 10:56 UTC, DARKDRAGON532 requested changes
instead of changing all that stuff just add 
`document.documentElement.lang || userLocales || navigator.language`

2021-12-13 18:07 UTC, evanreichard commented
The main issue is a `TypeError` when attempting to pass `undefined` into the URL constructor. I just added another commit to no longer default to `en`, as well as add the changes re: `navigator.language`.

Let me know if you think there's a better way.

<img width="559" alt="Screen Shot 2021-12-13 at 13 05 20" src="https://user-images.githubusercontent.com/30810613/145864956-99f6eb54-8a83-4928-adf5-04ce1b7497f7.png">

2021-12-14 03:50 UTC, DARKDRAGON532 commented
Atleast for me `document.body.lang` works on m.youtube.com, if its working for you then replace `document.documentElement.lang` with that

2021-12-14 12:57 UTC, evanreichard commented
> Atleast for me `document.body.lang` works on m.youtube.com, if its working for you then replace `null` in the ternary operator with that

Works for me as well. Just updated the PR with those changes.

2021-12-14 13:53 UTC, DARKDRAGON532 approved these changes

2021-12-14 22:23 UTC, merged