Add a security FAQ
Anarios/return-youtube-dislike pull request #348
Opened 2021-12-19 09:22 UTC by CallMeAlexO

I've noticed that as the extension gains popularity, more and more people are pouring over with legitimate security concerns - and they open the same issues asking the same questions.. So I figured it'd be nice to have a security FAQ.

2021-12-19 10:03 UTC, leonbubova approved these changes
Nice writeup 👌🏻

2021-12-19 12:34 UTC, UnderscoreX5 reviewed
Other than the 3 small changes I would personally make, I think this is a solid security FAQ that should be implemented.

2021-12-19 12:34 UTC, UnderscoreX5 commented on SECURITY.md
>  The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. This is done to prevent database vandalism.
on a hard or solid-state drive perhaps?

2021-12-19 12:34 UTC, UnderscoreX5 commented on SECURITY.md
>  This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
Could add a link to https://en.wikipedia.org/wiki/OAuth so that anyone that's curious enough can double check on their own

2021-12-19 12:34 UTC, UnderscoreX5 commented on FAQ.md
> +## I have security concerns
I have concerns regarding the security and anonimity of this extension (could perhaps sound better)

2021-12-19 14:23 UTC, CallMeAlexO commented on FAQ.md
> +## I have security concerns
Improved phrasing

2021-12-19 14:23 UTC, himanshudabas commented on SECURITY.md
> +No. The extension's code is public and you can see it for yourself. The only information being sent is the video ID. There are no additional headers being sent. Over the communication layer, your pub
> The only information being sent is the video ID.

can we instead say `The only information being sent is the video ID, which is required to fetch the dislike count for the videos.`, so that it doesn't give an impression that the video ID being sent is for tracking.

2021-12-19 14:23 UTC, himanshudabas commented on SECURITY.md
> +The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. This is done to prevent database vandalism.
I don't think we even keep IPs in plain text. I think we keep hashes of IPs.
@Anarios could you please clarify?

2021-12-19 14:23 UTC, himanshudabas commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
I think it's worth mentioning that OAuth hasn't been implemented yet.

2021-12-19 14:23 UTC, himanshudabas commented on SECURITY.md
> +Short answer is: you can't. We've implemented anti-botting measures, but at the end of the day, it's up to you to decide whether you trust our count or not.
Maybe be a little less direct here :)
instead write something like
```We have implemented measures to prevent bot attacks, and we are gonna continue to work on improving the effectiveness of the bot prevention system. This will help us keep the dislike count as a good representative of the actual count. Of course, it can never be 100% accurate. So it's up to you to decide whether you trust the count or not.```

2021-12-19 14:23 UTC, CallMeAlexO commented on SECURITY.md
>  This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
Great idea! Added.

2021-12-19 14:24 UTC, CallMeAlexO commented on SECURITY.md
>  The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. This is done to prevent database vandalism.
I think it's pretty clear. In this case hard drive is a synonym for any storage device.

2021-12-19 14:27 UTC, UnderscoreX5 commented on SECURITY.md
> +No. The extension's code is public and you can see it for yourself. The only information being sent is the video ID. There are no additional headers being sent. Over the communication layer, your pub
I agree

2021-12-19 14:28 UTC, UnderscoreX5 commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
Yeah, maybe change thefrasing like "This feature _will be_ optional" and just clarify that it's not out yet.

2021-12-19 14:28 UTC, CallMeAlexO commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
The goal of the security FAQ is to cover the security aspect of things, it isn't the changelog. Hopefully it shouldn't be updated that often. I think adding this in ahead of time can save a lot of people a lot of headaches in advance :)

2021-12-19 14:29 UTC, CallMeAlexO commented on SECURITY.md
> +No. The extension's code is public and you can see it for yourself. The only information being sent is the video ID. There are no additional headers being sent. Over the communication layer, your pub
Good catch!

2021-12-19 14:30 UTC, CallMeAlexO commented on SECURITY.md
> +Short answer is: you can't. We've implemented anti-botting measures, but at the end of the day, it's up to you to decide whether you trust our count or not.
I like this phrasing more, added!

2021-12-19 14:30 UTC, UnderscoreX5 commented on SECURITY.md
> +Short answer is: you can't. We've implemented anti-botting measures, but at the end of the day, it's up to you to decide whether you trust our count or not.
We have implemented measures to prevent bot attacks and are gonna continue to work on improving the effectiveness of the bot prevention system: this will help us keep the dislike count as a good representative of the actual count. Of course it will never be 100% accurate so it's up to you to decide whether you trust the count or not.

2021-12-19 14:32 UTC, UnderscoreX5 commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way [OAuth](https://en.wikipedia.org/wiki/OAuth#:~:text=
not sure whenever it's intentional or not but the link looks really messy and just lands on the same page as https://en.wikipedia.org/wiki/OAuth

2021-12-19 14:35 UTC, UnderscoreX5 commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
yeah but it could confuse people that want to partecipate into the OAuth thing + it takes no time to change once OAuth is rolled out

2021-12-19 14:40 UTC, CallMeAlexO commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way [OAuth](https://en.wikipedia.org/wiki/OAuth#:~:text=
It's intentional :) 
[Text Fragments](https://wicg.github.io/scroll-to-text-fragment/) are a new W3C proposal. Currently supported on most new browsers. It allows us to highlight text on the page. I highlighted the part where it says "without giving them the passwords". If you look at the page itself, that text should be highlighted in purple.

2021-12-19 14:41 UTC, himanshudabas commented on SECURITY.md
> +Short answer is: you can't. We've implemented anti-botting measures, but at the end of the day, it's up to you to decide whether you trust our count or not.
@CallMeAlexO could you please update it again with the phrasing UnderscoreX5 has suggested.

2021-12-19 14:43 UTC, UnderscoreX5 commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way [OAuth](https://en.wikipedia.org/wiki/OAuth#:~:text=
It doesn't show here on Firefox but since I use a hardened version of it I suppose it's just my issue so no worries then

2021-12-19 14:52 UTC, CallMeAlexO commented on SECURITY.md
> +Short answer is: you can't. We've implemented anti-botting measures, but at the end of the day, it's up to you to decide whether you trust our count or not.
Done.

2021-12-19 14:52 UTC, CallMeAlexO commented on SECURITY.md
> +This feature is optional, and very much opt-in. If you are a YouTube creator, and would like to share your dislike stats with us, you can. The way OAuth was structured, is it's actually very secure.
Done.

2021-12-19 15:01 UTC, UnderscoreX5 approved these changes
Unless there are some pretty small issues we didn't catch I think this is good to go! Well done!

2021-12-19 15:53 UTC, Anarios commented on SECURITY.md
> +The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. This is done to prevent database vandalism.
Yes, we do cap IP hashes. Un-hashed IPs are stored in-memory only, so this should be updated

2021-12-19 16:06 UTC, Anarios commented
We store IP hashes, so this needs to be mentioned as well.

2021-12-19 16:25 UTC, himanshudabas commented on SECURITY.md
> +The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. This is done to prevent database vandalism.
@CallMeAlexO please mention that we store only `IP Hashes` to prevent data vandalism from bad actors.
maybe add a wiki link as well for hashing.

2021-12-19 16:28 UTC, himanshudabas commented on SECURITY.md
>  The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. This is done to prevent database vandalism.
marking this as resolved as it's no longer valid. refer https://github.com/Anarios/return-youtube-dislike/pull/348/files#r771971987

2021-12-19 17:18 UTC, himanshudabas approved these changes
looks good to me.

2021-12-19 20:27 UTC, DARKDRAGON532 requested changes
`SECURITY.md` is usually for security politcy, rename the file to `SECURITY-FAQ.md` or something similar

2021-12-19 20:38 UTC, DARKDRAGON532 approved these changes

2021-12-19 20:58 UTC, merged

2021-12-19 20:58 UTC, Anarios commented
Thanks!

2021-12-19 21:10 UTC, Anarios commented
I removed the "hases can not be reversed" part, because I wouldn't be so sure when dealing with IPs (rainbow tables, etc). So, it complicates things a bit, but doesn't make it undoable. 

And I doubt there is anything we can do. Always open to ideas, though.

2021-12-20 02:36 UTC, ajayyy commented on SECURITY-FAQ.md
> +No. When you dislike a video, we create a unique (but random and non-identifiable) ID for you. This is done to prevent botting. But again, it cannot uniquely identify you.
How is a unique id "non-identifiable"?

```suggestion

Yes. When you dislike a video, we create a randomly generated unique ID for you that is not tied to your Google account. This is done to prevent botting.
```

2021-12-20 02:36 UTC, ajayyy commented on SECURITY-FAQ.md
> +The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. We hash the IP addresses, and that's stored instead. This is
```suggestion
The backend keeps IP addresses in volatile memory (RAM) only. These addresses aren't stored on a hard drive, and therefore aren't logged. We hash the IP addresses, and that's stored instead. This is done to prevent database vandalism. 

A hash is a one-way function, requiring guess and check to determine the original data. Since there are a limited set of IPV4 addresses (2^32), it is possible to reverse this hash, but hashing increases the effort required to do so.
```

2021-12-20 02:38 UTC, ajayyy commented
Oh, this is merged. Will make PR

2021-12-22 11:40 UTC, CagesThrottleUs commented
> And I doubt there is anything we can do. Always open to ideas, though.

Okay, I am no security expert and what I am going to say is from just normal searching "how to prevent reversing of a hash". 

So to prevent reverse hashing, I thought of treating it as a problem of password protection, where you would be protecting the dynamic IP with same level as a password. A standard hash function like SHA-256 etc. can be used but a lot of suggestion has been against it. 

Something that caught my eye is Argon2. It has been recommended via [PHC](https://www.password-hashing.net). But to implement Argon2, there are more security stuff like Salt, Parallelism, etc. A lot of this can be seen from [this webpage](https://argon2.online). I recommend that someone actually look into specification, time-cost etc. I will help with the limit of my abilities if required.

2021-12-22 12:08 UTC, Anarios commented
@CagesThrottleUs difference for IPs is that you know possible value range. So methods described here do not work so well for IPs. It's better with IPV6, but for IPV4 value range is quite limited.

2021-12-22 12:13 UTC, CagesThrottleUs commented
> @CagesThrottleUs difference for IPs is that you know possible value range. So methods described here do not work so well for IPs. It's better with IPV6, but for IPV4 value range is quite limited.

I see, perhaps the idea of salts may work with the current existing stuff. Anyway, hope you find something useful and thank you for taking time to view this.

2021-12-23 05:31 UTC, himanshudabas commented
> I see, perhaps the idea of salts may work with the current existing stuff. Anyway, hope you find something useful and thank you for taking time to view this.

Even if we add salts to the hashed IPs, that salt has to be consistent for all the IPs, else we won't have a way to map new requests to our hashed + salted IPs in our db.
We could use some function which takes the IP itself to compute a unique salt for each ip address.
that would certainly make the job difficult for hackers to map the hashed + salted addresses to their corresponding IPv4 addresses.

If backed gets somehow compromised, hackers could still get access to the function itself.
IPv4 are just over 4 billion. It'd be a relatively easy task for them to compute hash + salt of all available IPv4 addresses.

But I get your point, It's certainly better than simply storing sha512 hashes, as they are pretty easy & fast to compute.
`bcrypt` is better than `sha512`, `Argon2` is even better than `bcrypt` for this use case.

It is worth looking into to strengthen the backend.

2021-12-23 07:06 UTC, UnderscoreX5 commented
I do believe that hashing the IPs is surely beneficial but at the same time it's kinda a useless measure if you get what I mean. IPs aren't really ideal for hashing since they aren't infinite and there is actually a limited bunker of them. Furthermore what you are stealing is an IP connected to a random ID at max, there's little reason to since we already have a pool of more than a million users and that keeps growing. We can surely do it because more safety is better but stealing a random IP address of someone you can't even identify is like DDOSSING a random IP address you made up following the real parameters... useless.