Add version number to extension's menu (being worked)
Anarios/return-youtube-dislike pull request #351
Opened 2021-12-19 15:09 UTC by UnderscoreX5

I added the version number I found in the manifest. Currently testing different text sizes and placements but I think this placement can work.

2021-12-19 16:00 UTC, himanshudabas requested changes

2021-12-19 16:00 UTC, himanshudabas commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
instead of hardcoding, you might wanna use `chrome.runtime.getManifest().version;`

2021-12-19 16:01 UTC, himanshudabas commented
cc https://github.com/Anarios/return-youtube-dislike/issues/350

2021-12-19 16:04 UTC, Anarios commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
and not chrome, but cross-browser version

2021-12-19 16:09 UTC, UnderscoreX5 commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
Yeah that's better. Will change it as soon as I can.

2021-12-19 16:13 UTC, UnderscoreX5 commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
I know that the namespace for firefox and safari is 'browser' but is there a cross-browser one fir both chromium and firefox/safari?

2021-12-19 16:34 UTC, himanshudabas commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
this is how we do this in bg-script:

https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/ryd.background.js#L11

try to test it in both browsers.

2021-12-19 16:50 UTC, UnderscoreX5 commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
It shouldn't work or at least not as efficiently, perhaps implementing it this way is better, coming up in seconds with a possible fix.

2021-12-19 16:57 UTC, UnderscoreX5 commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
@himanshudabas can you propose the 'chrome.runtime.getManifest().version;' change you did so I can double check on my firefox as well?

2021-12-19 17:11 UTC, himanshudabas commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
popup.html

```html
<p id="ext-version"></p>
```

popup.js

```javascript
function initConfig() {
  initializeVersionNumber();
  ...
}

...

function initializeVersionNumber() {
  const version = chrome.runtime.getManifest().version;
  document.getElementById('ext-version').innerHTML = 'v' + version;
}
```

2021-12-19 21:02 UTC, Anarios commented
> @Anarios I just tested chrome.runtime.getManifest().version; in firefox. I don't know why but it works (:

I think it works in later FF versions, but might break in older ones, which would otherwise work. I'm not sure though.

2021-12-19 21:25 UTC, UnderscoreX5 commented
I suppose that the best way is then to use both browser and chrome namespaces just to be sure it works on all browsers (it works on firefox but what about safari?). Will try something tomorrow after work.

2021-12-19 21:32 UTC, Anarios commented
I think what we do in background.js can work here as well

2021-12-20 05:38 UTC, UnderscoreX5 commented
Yeah it probably works just gotta translate it to html tho

2021-12-20 12:35 UTC, UnderscoreX5 commented on Extensions/combined/popup.html
> +      <p>v2.0.0.3</p>
I implemented this for now.

2021-12-20 12:55 UTC, UnderscoreX5 commented
The current version doesn't work on my firefox but I think I've misplaced the function.

2021-12-27 08:03 UTC, Anarios approved these changes

2021-12-27 08:04 UTC, merged