change dislike filed removal to "has been removed"
Anarios/return-youtube-dislike pull request #365
Opened 2021-12-23 17:39 UTC by thesusian

changing that the dislike field in the YouTube API from "will be removed" to "has been removed" in README

2021-12-24 01:56 UTC, Nightcaat requested changes
I think _was_ would fit better here

2021-12-24 11:21 UTC, thesusian commented
done

2021-12-25 21:59 UTC, pedrogleta approved these changes

2021-12-27 08:20 UTC, Anarios approved these changes

2021-12-27 08:20 UTC, merged