Fixed issue #389
Anarios/return-youtube-dislike pull request #395
Opened 2022-01-01 05:39 UTC by thesusian

Fixed issue #389 with dislikes count showing up as 0 on videos that have the like and dislike count hidden by the creator

2022-01-01 06:34 UTC, cupiditys commented
sometimes says "dislikes disabled" even on videos with ratings on
![image](https://user-images.githubusercontent.com/66990287/147845254-96b5207c-9b02-4fd5-b5b7-e6f455723f58.png)

2022-01-01 07:40 UTC, thesusian commented
can you share the video link / browser, It's seems to be working fine for me.
tested on (Mozilla Firefox 95.0.2) and (Chromium 96.0.4664.110)

2022-01-01 19:34 UTC, cupiditys commented
im not sure exactly what causes it since when i refreshed it was fixed but just happened randomly when i clicked on a video

2022-01-02 19:44 UTC, Anarios commented
Remove /dist folder - it's in gitignore now.

2022-01-06 23:20 UTC, PickleNik requested changes
Remove the /dist folder from committed files please :)

2022-01-07 10:01 UTC, thesusian commented
Removed /dist

2022-01-08 14:40 UTC, Anarios commented on Extensions/combined/src/bar.js
> +    } else {
Coule you please apply Prettier styles? Lots of changes with only spaces, hard to read a PR, thanks!

2022-01-08 15:26 UTC, PickleNik commented
@Anarios

2022-01-08 15:37 UTC, thesusian commented on Extensions/combined/src/bar.js
> +    } else {
Done and commited

2022-01-08 15:46 UTC, merged

2022-01-08 15:46 UTC, Anarios commented
Thanks!