Add custom number formats
Anarios/return-youtube-dislike pull request #435
Opened 2022-01-11 23:17 UTC by cyrildtm

Fix Issues #201 #364 #407
Using plugin options (Issue #387)

2022-01-12 02:00 UTC, cyrildtm commented
Certain locales may display like number without rounding down. See: issue #364
```
Intl.NumberFormat('de', {notation: 'compact', compactDisplay: 'short'}).format(123456)
'123.456'
```

2022-02-04 19:19 UTC, Anarios requested changes
Some code is copy-pasted, is it possbile to get rid of duplicates?

2022-02-04 19:19 UTC, Anarios commented on Extensions/combined/popup.js
> +function getNumberFormatter(optionSelect) {
same function down below?

2022-02-04 21:44 UTC, cyrildtm commented on Extensions/combined/popup.js
> +function getNumberFormatter(optionSelect) {
It provides the same function but at a different place. The main feature is in util.js that works in the user's window (youtube.com) / content script; while this one in popup.js works in the extension's popup interface. 
I added this function (and others alike) to show an example of what the user really sees using their locale settings. 

I tried to import these functions from util.js or other files into popup.js and vice versa, but got errors.

2022-02-04 21:53 UTC, cyrildtm commented on Extensions/combined/popup.js
> +function getNumberFormatter(optionSelect) {
Otherwise there's a code-sharing scheme [like this one](https://stackoverflow.com/a/24227952/3839249) but that looks as messy as this one. Let me know if there's any other way of implementing one function in both places at once, and I can make the change.

2022-03-20 17:32 UTC, Anarios commented
Thanks a lot

2022-03-20 17:32 UTC, merged