Added YouTube tutorial to contribution guide
Anarios/return-youtube-dislike pull request #514
Opened 2022-03-20 22:46 UTC by RyannDaGreat

I've added a YouTube tutorial addressing https://github.com/Anarios/return-youtube-dislike/issues/510

2022-03-23 21:16 UTC, krystian3w commented on CONTRIBUTING.md
> +x# Welcome To Return YouTube Dislikes contributing guide
what is that

2022-03-23 21:18 UTC, krystian3w requested changes
<!-- -->

2022-03-23 21:51 UTC, RyannDaGreat commented on CONTRIBUTING.md
> +x# Welcome To Return YouTube Dislikes contributing guide
Oh my! That's a typo lol...thank you!

2022-03-23 22:16 UTC, krystian3w approved these changes

2022-04-10 15:05 UTC, JacksonChen666 commented
this pr, i would assume, resolves #510 

(using specific keywords and mentioning an issue will close the respective issue when the pr is merged)

2022-04-11 04:03 UTC, sy-b commented
Just a test

fixes #514

2022-04-18 04:13 UTC, cyrildtm commented
> (probably)

[yes](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2022-04-21 18:20 UTC, ErykDarnowski approved these changes

2022-04-26 16:28 UTC, merged