Added German translation
Anarios/return-youtube-dislike pull request #546
Opened 2022-04-18 15:42 UTC by aaronkerckhoff

Since I'm a native German speaker, I decided to add a German translation to the locales.

2022-04-18 15:45 UTC, sy-b approved these changes

2022-04-18 17:03 UTC, FlorianPanten requested changes
Just some improvement suggestions

2022-04-18 19:14 UTC, aaronkerckhoff commented on Extensions/combined/_locales/de/messages.json
> +      "message": "Likes/Dislikes nicht einreichen"
Yes, sounds better. Thank you

2022-04-18 19:15 UTC, aaronkerckhoff commented on Extensions/combined/_locales/de/messages.json
> +      "message": "Bringt die Möglichkeit zurück, Dislikes zu sehen"
This actually was my first version but I then decided to change it literally. But yes, maybe this is better.

2022-04-18 19:18 UTC, aaronkerckhoff commented on Extensions/combined/_locales/de/messages.json
> +      "message": "Website"
I thought about that, but I thought that this sounds a bit too formal. Personally, I don't know anyone who says "Webseite". But yes, maybe that still would be better.

2022-04-18 19:26 UTC, aaronkerckhoff commented
> Just some improvement suggestions

Thank you very much for the suggestions. I changed the first two and currently considering the third one. Maybe another German native speaker can say how they'd rather translate "Website".

2022-04-18 20:05 UTC, chludek commented on Extensions/combined/_locales/de/messages.json
> +      "message": "Website"
I would definitely still use "Website". As you said, "Webseite" sounds way too formal. If you really take it this far, you probably would have to translate words like "FAQ" or "Likes/Dislikes" as well. The remaining translations look also good for me 👍

2022-04-18 20:10 UTC, chludek approved these changes

2022-04-18 20:11 UTC, aaronkerckhoff commented on Extensions/combined/_locales/de/messages.json
> +      "message": "Website"
Thank you very much for another opinion, so I think I'm going to leave it as "Website".

2022-04-19 01:23 UTC, FlorianPanten approved these changes

2022-04-19 03:41 UTC, sy-b approved these changes

2022-04-26 16:46 UTC, merged