ESLint integration
Anarios/return-youtube-dislike pull request #67
Opened 2021-11-27 16:51 UTC by DmACKGL

Its always recommended to use ESLint when is possible.

2021-12-02 21:40 UTC, gitdev-bash approved these changes
Can verify everything but the dependency file ```Website/package-lock.json```.
Am not sure if ```Website/pages/links.vue``` line 9 breaks something.

2021-12-02 21:40 UTC, gitdev-bash commented on Website/pages/links.vue
> +            <p style="margin-bottom: 1em">
Does this break something?

2021-12-02 22:40 UTC, PickleNik commented on Website/pages/links.vue
> +            <p style="margin-bottom: 1em">
I don't see why it would, just moves it to the next line.
Though it does create conflicts for merge.
It would be ideal to leave the config files in and formatted files out.

2021-12-02 23:22 UTC, PickleNik commented
> Can verify everything but the dependency file `Website/package-lock.json`. Am not sure if `Website/pages/links.vue` line 9 breaks something.

Why do you think it would break something?

2021-12-02 23:28 UTC, PickleNik requested changes
Could you remove formatted `.vue` files from commit? Or pull recent and re-format those. (to avoid conflicts)
Config files seem fine to me 👍🏼

2021-12-04 00:17 UTC, Kefta commented
Contains unnecessary changes and semantical edits.

2021-12-04 22:01 UTC, PickleNik approved these changes

2021-12-08 09:02 UTC, gitdev-bash commented
> Contains unnecessary changes and semantical edits.

Is a Lint unnecessary?

2021-12-12 22:35 UTC, PickleNik commented
This has been hanging for a couple weeks, so I re-implemented it in #280 , thanks for the suggestion tho

2021-12-12 22:35 UTC, closed without merging