Add Dutch translation.
Anarios/return-youtube-dislike pull request #768
Opened 2022-10-03 16:06 UTC by JxxIT

This adds an Dutch translation.

2022-10-24 23:10 UTC, YassineGherbi commented on CONTRIBUTINGnl.md
> +- Typfouten of betere en gemakkelijkere woorden om te gebruiken.
Ironic haha. Het is "Typefouten" ipv "Typfouten" :)

2022-10-24 23:13 UTC, YassineGherbi commented on Docs/FAQnl.md
> +De backend zal overschakelen naar het gebruik van een combinatie van gearchiveerde afkeerstatistieken, schattingen geëxtrapoleerd uit gebruikersgegevens van extensies en schattingen op basis van weer
Correct spelling should be "afkeer statistieken" en "afkeer archieven" if I am really 'aan het mierenneuken'

2022-10-24 23:14 UTC, YassineGherbi commented on Docs/FAQnl.md
> +See [this page](SECURITY-FAQ.md) for more info.
Maybe we could also translate this sentence? Or did you skip it for a reason?

2022-10-24 23:16 UTC, YassineGherbi requested changes
2 small spelling mistakes but awesome work! Do we really need 6 approvals? Seems like to lot to me, tbh. @Anarios

2022-10-25 06:21 UTC, JxxIT commented
If fixed the typos.

2022-10-25 21:08 UTC, OpenSourceSimon approved these changes

2022-11-01 21:39 UTC, YassineGherbi approved these changes

2022-11-01 21:40 UTC, YassineGherbi commented
I would suggest tagging some people who could also review. You'll need 5 more approving reviews to be able to merge this automatically

2022-11-02 18:10 UTC, JxxIT commented
Yes, but who can approve it?

2023-02-18 17:43 UTC, merged